language: node_js
node_js:
  - "6"
dist: trusty # needs Ubuntu Trusty
sudo: false  # no need for virtualization.
before_install:
  - npm install -g npm@latest
  - npm install -g greenkeeper-lockfile@1
install:
  - npm install
sudo: required
addons:
  chrome: stable # install chrome stable.
cache:
  yarn: true
  directories:
    - $HOME/.npm
before_script:
  - greenkeeper-lockfile-update
  - npm run lint
script:
  - npm run coverage
after_script:
  - greenkeeper-lockfile-upload
after_success:
  - npm run coveralls